package com.sslwireless.sslcommerzlibrary.view.custom;

import android.text.Editable;
import android.text.TextWatcher;

/**
 * Autogenerated, do not edit. All changes will be undone.
 * Created by Prokash Sarkar on 8/12/18.
 */
public abstract class SSLCCustomTextWatcher implements TextWatcher {

    private int lastLength, lastLength2;

    public abstract void afterTextChanged(Editable s, boolean backSpace, boolean lastLength);

    public abstract void onTextChanged(boolean lastLength);

    @Override
    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
        lastLength = s.length();
    }

    @Override
    public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
        lastLength2 = i2;
        onTextChanged(i2 > 0);
    }

    @Override
    public void afterTextChanged(Editable s) {
        afterTextChanged(s, lastLength > s.length(), lastLength2 > 0);
    }
}